vendor_app/urls.py
from django.urls import path
from .views import vendor_create, vendor_list

app_name = 'vendor'

urlpatterns = [
    path('', vendor_create, name='vendor'),
    path('list/', vendor_list, name='vendor_list'),
]

vendorproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vendor_app.urls', namespace='vendor')),
]

vendor_app/models.py
from django.db import models


# Create your models here.
class Vendor(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    contact_no = models.BigIntegerField()

    def __str__(self):
        return self.name


class VendorAddress(models.Model):
    vendor_id = models.ForeignKey(Vendor, on_delete=models.CASCADE)
    vendor_addr = models.TextField(max_length=200)

vendor_app/views.py
from django.shortcuts import render
from .models import Vendor, VendorAddress
from .form import VendorForm, VendorAddrForm
from django.db import transaction, IntegrityError
from django.forms import modelformset_factory


# Create your views here.
def vendor_create(request):
    form = VendorForm(request.POST or None)
    addrform = VendorAddrForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid() and addrform.is_valid():
            try:
                with transaction.atomic():
                    insured = form.save(commit=False)
                    insured.save()
                    data = addrform.save(commit=False)
                    data.vendor_id = insured
                    data.save()
            except IntegrityError:
                print("Error Encountere d",IntegrityError.__name__)
    form = VendorForm()
    addrform = VendorAddrForm()
    context = {
        'form': form,
        'addrform': addrform
    }
    return render(request, 'vendor.html', context)


def vendor_list(request):
    vendor = Vendor.objects.all()
    vaddr = VendorAddress.objects.all()
    q = vendor.union(vaddr)
    return render(request, 'vendor_list.html', {'q': q})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block block_title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/vendor.html
{% extends 'base.html' %}
{% block block_title %}Vendor Create{% endblock %}
{% block content %}
<h1 class="text-center">Vendor Details Here...</h1>
<div class="container">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {{ addrform.as_p }}
    <input type="submit" href="{% url 'vendor:vendor_list' %}">
</form>
</div>
{% endblock %}

templates/vendor_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table border="2">
<tr>
    <th>Vendor Name</th>
    <th>Vendor Email</th>
    <th>Vendor Contact No.</th>
    <th>Vendor Address</th>
</tr>

<tr>
    {%  for vd in q %}
    <td>{{ vd.name }}</td>
    <td>{{ vd.email }}</td>
    <td>{{ vd.contact_no }}</td>
    <td>{{ vd.vendor_addr }}</td>
</tr>
{% endfor %}
</table>
</body>
</html>